# Generated by Django 6.0.3 on 2026-06-24 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0003_add_keluarga_fk_to_member"),
        ("payments", "0004_rename_date_paid_payment_date_received_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("member__isnull", False),
                    ("keluarga__isnull", False),
                    _connector="OR",
                ),
                name="payment_must_have_member_or_keluarga",
            ),
        ),
    ]
