# Generated by Django 5.2.15 on 2026-06-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keluarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kk_number", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "lingkungan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="keluarga_set",
                        to="members.lingkungan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Keluarga",
                "ordering": ["lingkungan__name", "kk_number"],
            },
        ),
    ]
