# Generated by Django 6.0.3 on 2026-06-19 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_keluarga"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="keluarga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="members.keluarga",
            ),
        ),
    ]
